### ISSUE TITLE
Unable to record in docker container based on Ruby 3

### ISSUE THREAD

**Issue by mscrivo** [rbspy/rbspy#325]
We've had great success with using rbspy on our Ruby 2.7 app running in docker containers using the ruby-slim docker image. I've been anxiously awaiting being able to use it again since it stopped working after we upgraded to ruby 3. However, with the latest 0.60 release, I'm running into the following issue:

```
Warning: no profile samples were collected
Error. Causes:
- Couldn't get ruby version: Couldn't determine Ruby version

Caused by:
    0: Operation not permitted (os error 1)
    1: Operation not permitted (os error 1)
Couldn't get ruby version: Couldn't determine Ruby version

Caused by:
    0: Operation not permitted (os error 1)
    1: Operation not permitted (os error 1)
```
when running with `record -p 1`

Running on my macOS machine, it works just fine, so something specific to the linux container.  Happy to provide more info for troubleshooting, just don't know what else would be helpful.

I'm running the `rbspy-x86_64-unknown-linux-gnu` binary for reference.

**Comment by acj** [comment]
Is your container running with the `SYS_PTRACE` capability? I can repro the error you mentioned if I run the ruby:3.0.1-slim image in Docker with the default options. If I include `--cap-add=SYS_PTRACE`, then rbspy is able to sample processes correctly.

I'm not sure why this would have changed with Ruby 3, though. Did you change anything else at the same time? Container runtime or other upgrades?

**Comment by mscrivo** [comment]
Thanks @acj ... we did recently upgrade our k8s version and that switched the container runtime from docker to containerd, possible that was it? I believe I ran into this issue before we did that upgrade though, but impossible for me to verify now.

Anyhow, good to know that it should be working. I tried configuring my deployment with:

```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - SYS_PTRACE
      privileged: false
      runAsNonRoot: true
      readOnlyRootFilesystem: false
```

but it's still not working. I will dig in further tomorrow now that I have a lead and hopefully figure it out.
